---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: javacontainer
        image: sukeshguna942/image58
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  type: NodePort
  selector:
    app: java
  ports:
  - port: 8070
    targetPort: 8080
    nodePort: 30001



    

